pets/src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Nome = null;

    #[ORM\Column(type: 'decimal', precision:10, scale: 2)]
    private ?float $Idade = null;

    #[ORM\ManyToOne(targetEntity: Raca::class, inversedBy: 'animals')]
    #[ORM\JoinColumn(nullable:false, onDelete: 'CASCADE')]
    private ?Raca $raca = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $foto = null;

    #[ORM\ManyToOne(targetEntity: AnimalTipo::class, inversedBy: 'animals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AnimalTipo $Tipo = null;

    #[ORM\ManyToOne(targetEntity: Tutor::class, inversedBy: 'animais')]
    private ?Tutor $tutor = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cliente $cliente = null;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->Nome;
    }

    public function setNome(string $Nome): static
    {
        $this->Nome = $Nome;

        return $this;
    }

    public function getIdade(): ?float
    {
        return $this->Idade;
    }

    public function setIdade(float $Idade): static
    {
        $this->Idade = $Idade;

        return $this;
    }

    public function getRaca(): ?Raca
    {
        return $this->raca;
    }

    public function setRaca(?Raca $raca): self
    {
        $this->raca = $raca;

        return $this;
    }

    public function getFoto() : ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto) : self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getTipo(): ?AnimalTipo
    {
        return $this->Tipo;
    }

    public function setTipo(?AnimalTipo $Tipo): static
    {
        $this->Tipo = $Tipo;

        return $this;
    }

    public function getTutor(): ?Tutor
    {
        return $this->tutor;
    }

    public function setTutor(?Tutor $tutor): static
    {
        $this->tutor = $tutor;

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): static
    {
        $this->cliente = $cliente;

        return $this;
    }
}

pets/src/Controller/AnimalController.php
<?php 

namespace App\Controller;

use App\Entity\Animal;
use App\Entity\Raca;
use App\Form\AnimalFormType;
use App\Repository\AnimalRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class AnimalController extends AbstractController{
    
    
    #[Route('/animal', name:'app_animal')]
    public function index(AnimalRepository $animalRepository, Request $request, EntityManagerInterface $em) : Response
    {
        $msg = "";
        $animal = new Animal();
        $form = $this->createForm(AnimalFormType::class, $animal, ['method' => 'GET']);
        $form->handleRequest($request);

        try{
            if ($form->isSubmitted() && $form->isValid()){
                $raca = $form->get('raca')->getData();
                if ($raca instanceof Raca) {
                    $animal->setRaca($raca);
                }
                

                $em->persist($animal);
                $em->flush();
                $msg = 'Animal cadastrado com sucesso !';
            }
        }catch(Exception $e){
            $msg = 'Erro ao cadastrar animal';
        }

        $this->denyAccessUnlessGranted("ROLE_USER");
        $data['animais'] = $animalRepository->findAll();        
        $data['titulo'] = 'Lista de Animais';
        $data['animalForm'] = $form;
        $data['msg'] = $msg;

        return $this->render('animal/index.html.twig', $data);

    }
}

?>

pets/templates/animal/index.html.twig
{% extends "base.html.twig" %}
{% block title %}
    {{ titulo }}
{% endblock %}

{% block body %}
  
    <h1> {{ titulo }} </h1>


<button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#formSection" aria-expanded="false" aria-controls="formSection">
  Novo
</button>
{{ msg }}


<div class="collapse" id="formSection">
  <div class="card card-body mt-3">
    <form>
        {{ form_start(animalForm) }}
      <div class="mb-3">
        <h2>Cadastro de Animal</h2>
      </div>
      <div class="mb-3">
        {{ form_row(animalForm.nome) }}
        {{ form_row(animalForm.tipo) }}
        {{ form_row(animalForm.raca) }}
        {{ form_row(animalForm.idade) }}
        {{ form_row(animalForm.foto) }}
        <button type='submit' class='btn btn-success'>Salvar</button>
      </div>
      {{ form_end(animalForm) }}
    </form>
  </div>
</div>

    <table class='table'>
        <thead>
            <tr>
                <td>Id</td>
                <td>Nome</td>
                <td>Idade</td>
                <td>Tipo</td>
                <td>Raça</td>
                <td>Ações</td>
            </tr>
        </thead>
        <tbody>
            {% for animal in animais %}
                <tr>
                    <td>{{ animal.Id }}</td>
                    <td>{{ animal.Nome }}</td>
                    <td>{{ animal.Idade }}</td>
                    <td>{{ animal.tipo.nome}}</td>
                    <td>{{ animal.raca.nome }}</td>
                    <td>
                      <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse">
          <i class="bi bi-pencil-square"></i>
        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}